var blankLine = ' | | ';
console.log('This is what an empty board will look like');
console.log(blankLine);
console.log(blankLine);
console.log(blankLine);
var guessLine = '1| | ';
var bombLine = ' |B| ';
console.log('This is what a board ,ight look like during a game');
console.log(guessLine);
console.log(bombLine);
console.log(blankLine);
